### ISSUE TITLE
Rearranging the files 

### ISSUE THREAD

**Issue by theDreamer911** [bandya2003/MLProjectTraining#103]
This repos contains great datasets from many sources. But, I see there are new-comer adding it without considering the tidiness of the repository, may I tidy this repository by sorting each topic of the dataset?

**Comment by bandya2003** [comment]
Please work on it

**Comment by theDreamer911** [comment]
alright, if you don't mind, please assign it to me

**Comment by bandya2003** [comment]
Done 👍

**Comment by theDreamer911** [comment]
Thank you, I hope my work can be used. So the new PR will be tidier.
