### ISSUE TITLE
Please add the images in the Code into Laptop folder

### ISSUE THREAD

**Issue by bandya2003** [bandya2003/MLProjectTraining#200]
Would be really helpful if someone merged the laptop images into their specified Folder.

![image](https://user-images.githubusercontent.com/61108642/198590562-ae324961-ac44-4056-9bb1-6c284e83de4c.png)

These images need to be added into the laptop Folder

**Comment by bandya2003** [comment]
@theDreamer911  can you please fix it?
would be really helpful

**Comment by itsekta** [comment]
@bandya2003 these are already present in laptop folder

**Comment by bandya2003** [comment]
> @bandya2003 these are already present in laptop folder

Please delete the images which aren't into the folder then

**Comment by itsekta** [comment]
> > @bandya2003 these are already present in laptop folder
> 
> Please delete the images which aren't into the folder then

Ok

**Comment by itsekta** [comment]
(https://github.com/bandya2003/MLProjectTraining/pull/234) This will close the issue.
