### ISSUE TITLE
Add the images without folder 

### ISSUE THREAD

**Issue by bandya2003** [bandya2003/MLProjectTraining#74]
In the code section you can see a few images that aren't a part of folder 
would be really helpful if you can add the images in a folder

**Comment by Atharva-cyber-dark** [comment]
Assign

**Comment by tmsagarofficial** [comment]
@bandya2003 pls assign me this issue so that I can also contribute

**Comment by bandya2003** [comment]
@tmsagarofficial please work  on it

**Comment by tmsagarofficial** [comment]
@bandya2003 Hi again, Thanks for assigning. Will start working on this now.
